version: '3.9'

services:
  dev:
    container_name: nestjs_api_dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mysql
  prod:
    container_name: nestjs_api_prod
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    ports:
      - 3306:3306
    volumes:
      - ./../.db/mysql/data:/var/lib/mysql
      - ./../.db/mysql/conf:/etc/mysql/conf.d
      - ./../.db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: pwteam07
      MYSQL_DATABASE: market
      MYSQL_USER: team07
      MYSQL_PASSWORD: pwteam07
networks:
  webnet:
volumes:
  msdata:
